f = open('test.txt', 'r+')
# print(f.name)
# print(f.mode)
# f.write('Hello Python-2021')
# f.write('Learning Python from Bohubrihi.')
# content = f.read(12)
content = f.tell()
# content = f.seek(0)
print(content)
f.close()
# print(f.closed)
