import os
# print(dir(os))
# print(os.getcwd())
#os.mkdir()
#os.makedirs('a/b/c/d')
#os.remove('filePath')
#os.rmdir('directoryName')
#os.rename('oldFileName', 'newFileName')
#os.path
#os.path.basename('filePath')
#os.path.dirname('filePath')
#os.path.exists('file/directory')
#os.path.exists('file')
#os.path.isdir('directory')
#os.path.isfile('file')
#os.path.join(directory, 'fileName')
#os.path.split('fullPath')
